### ISSUE TITLE
Envoy-S Metered ?

### ISSUE THREAD

**Issue by Neowam** [vincentwolsink/home_assistant_enphase_envoy_installer#101]
Dear Vincent,

How do I know if I have a Envoy-S Metered situation to enable real time updates?

![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/94406673/a9f5592c-d804-4f5e-84b2-f20a7af69703)

**Comment by vincentwolsink** [comment]
Hi @Neowam, go to your Envoy device in Home Assistant, under “Apparaat info” it should say “Envoy-S Metered (with CT)”

**Comment by Neowam** [comment]
![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/94406673/3ceafa36-4c75-4651-a76e-099b13a288c0)

Do you mean this view?

**Comment by vincentwolsink** [comment]
Yes. So you have an Envoy-S Standard and won’t be able to use these features.
