### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Fasior** [vincentwolsink/home_assistant_enphase_envoy_installer#109]
**Describe the bug**

 When adding the integration, there is no description of the 4 fields. And what information should be added.

**Comment by vincentwolsink** [comment]
Did you have another variant of an Enphase integration installed before? Make sure you fully remove the `custom_components/enphase_envoy` directory before installing this one. I just tested again, it should look like this.

<img width="607" alt="Scherm­afbeelding 2024-02-24 om 10 20 11" src="https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/1639734/e00526e3-3937-4cdf-b47b-9f5607d8bc5e">
