### ISSUE TITLE
Lot's of status changes (not available)

### ISSUE THREAD

**Issue by posixx** [vincentwolsink/home_assistant_enphase_envoy_installer#13]
I see a lot of disconnects using this integration for the last week now. Every device (gateway. relay and inverters) often disconnects resulting in not available for some time. This happens about every hour.

![afbeelding](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/2280400/468488d2-e09b-4021-a838-852602960ab0)

**Comment by posixx** [comment]
No nothing that i'm aware of. On PC and Phone  i use owner account when using enlighten.

**Comment by vincentwolsink** [comment]
Does this happen only for the binary sensors (producing/communicating) or also for the other sensors? And how many solar panels do you have installed?

**Comment by vincentwolsink** [comment]
Interesting, because it claims the token validity is a year there. Owner tokens are valid for a year, installer tokens only for 12 hours. Your installer account, is it a true installer account or a DHZ one?

Can you also maybe give a bit more context around this? The HTTP request just before the token refresh for example.

**Comment by posixx** [comment]
I have a installer account no DHZ. You can download the log here: https://saasgui.yodacloud.net/sharing/bM1ezvaOe

Let me know if you got it; the link can be used only once..

**Comment by vincentwolsink** [comment]
@posixx The url returns a page not found.

**Comment by posixx** [comment]
Well then someone else has downloaded it. Sorry i don't have any mailadres or someting to reach you

**Comment by posixx** [comment]
> Hi @posixx, do you have any other script/integration/job running that uses the installer account to connect to your Envoy? The Envoy only allows one installer session at a time.

I have created an installer account and connected it to my system. The original installer (the company who installed panels and configured everything) also still has connection to my system. Could that be the issue? Cannot imagine this would cause the problem as this installer doesn’t have access to internal ip etc..

**Comment by vincentwolsink** [comment]
The limitation is on the local connection. The installer company uses the Enphase cloud so that is not an issue.

Can you please send the debug log to this (temporary) email: ziener06joduur@icloud.com

**Comment by posixx** [comment]
Done!

**Comment by vincentwolsink** [comment]
Thanks. In the logfile I see it is reusing the token like it should, but suddenly at 16:01 it either starts another update parallel to the regular one, or it crashed halfway during the run and lost the token (although I don't see any exceptions or errors).

Which version of Home Assistant are you running?

**Comment by posixx** [comment]
> Thanks. In the logfile I see it is reusing the token like it should, but suddenly at 16:01 it either starts another update parallel to the regular one, or it crashed halfway during the run and lost the token (although I don't see any exceptions or errors).
> 
> Which version of Home Assistant are you running?

Latest, 2023.5.3

Also, every day at exactly 23:00 and/or 0:00 i get a timeout on the envoy:

2023-05-16 23:00:42.448 ERROR (MainThread) [custom_components.enphase_envoy] Timeout fetching envoy Envoy xxxxxxxxxxxxxx data
2023-05-17 23:01:36.229 ERROR (MainThread) [custom_components.enphase_envoy] Timeout fetching envoy Envoy xxxxxxxxxxxxxx data
2023-05-18 23:01:46.359 ERROR (MainThread) [custom_components.enphase_envoy] Timeout fetching envoy Envoy 122220065544 data
2023-05-19 00:01:19.357 ERROR (MainThread) [custom_components.enphase_envoy] Timeout fetching envoy Envoy xxxxxxxxxxxxxx data
2023-05-20 23:01:47.160 ERROR (MainThread) [custom_components.enphase_envoy] Timeout fetching envoy Envoy xxxxxxxxxxxxxx data
2023-05-21 00:01:25.252 ERROR (MainThread) [custom_components.enphase_envoy] Timeout fetching envoy Envoy xxxxxxxxxxxxxx data
2023-05-22 00:00:49.062 ERROR (MainThread) [custom_components.enphase_envoy] Timeout fetching envoy Envoy xxxxxxxxxxxxxx data

**Comment by vincentwolsink** [comment]
The timeout on the Envoy must be something outside the integration, so either on the Envoy itself, the network etc. I cannot reproduce the issue with the token currently. It is very suspicious that the token issue happens every hour. Actually the code around tokens did not change between this and your integration at all. What if you run your own versions of the integration with your installer account, does it also have the issue? And what about if you run it with your owner account?

**Comment by posixx** [comment]
I never used my own fork with the D7 firmware; i switched over to yours. Also i didn't touch the token code nor did i look at it to understand it; i only expanded the repo from brian to include the 3-phase sensors. I will do some test if i find the time for it.

**Comment by posixx** [comment]
I switched to my fork with installer login and will update tomorrow.

**Comment by posixx** [comment]
Vincent,

Not a single disconnect using my fork for mort than a day:

![afbeelding](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/2280400/13a8c286-0764-4aad-a45f-d87d54944701)

The timeout messages are still there in the HA log at 23u or 00u.

**Comment by vincentwolsink** [comment]
Then the issue is not in the token code, since that didn’t change between forks. Maybe something with the high number of sensors. But currently I have no way of debugging this since I cannot reproduce the issue.

**Comment by posixx** [comment]
OK, then i will continue to use my fork for now..

**Comment by vincentwolsink** [comment]
@posixx You could also help me and maybe others by doing some debugging for me, since you are also somewhat familiar with the code.
