### ISSUE TITLE
Failed setup, will retry: Login did not succeed

### ISSUE THREAD

**Issue by hapklaar** [vincentwolsink/home_assistant_enphase_envoy_installer#146]
Probably not a bug, but after updating to the latest version I get ```Failed setup, will retry: Login did not succeed```

I want to relogin and get a new token, but can't seem to find how to do this without removing the integration. How should this be done?

**Comment by vincentwolsink** [comment]
Could be a bug, since the login procedure for a home owner account changed internally. Wat kind of account do you use? And what is the firmware version of you Envoy?

If you want to re-enter your credentials you need to remove and re-add the integration. All history etc will be kept.

**Comment by hapklaar** [comment]
Envoy: Firmware: D8.2.4264

Did ultimately remove and added it back, but unfortunately lost all history. Might have done it wrong, I removed the HUB instead of the integration:

![image](https://github.com/user-attachments/assets/7417ee23-b362-4079-859a-db114e5e64ce)

**Comment by vincentwolsink** [comment]
History should not be lost. Maybe the sensors where named differently before? Then you would have to rename the new ones back.
