### ISSUE TITLE
[BUG]  after 9.2 unable to load 

### ISSUE THREAD

**Issue by TGgrimreaper** [vincentwolsink/home_assistant_enphase_envoy_installer#156]
**Describe the bug**

**Account type**
- [ x] Installer
- [ ] DIY / DHZ
- [x ] Home Owner (This integration is not (fully) functional with a home owner account!)

**Envoy**
- [ x] Metered with CTs installed
- [ ] Metered without CTs
- [ ] Standard

- FW version: D7.xxx
- Amount of micro inverters connected: 12

**Home Assistant**
- Version: 2024.9.2

**Additional context**
```
Envoy *************

Geen apparaten of entiteiten

Instellen mislukt, wordt opnieuw geprobeerd: 'NoneType' object has no attribute 'status_code



Relevant snippet of Home Assistant error log. 
```

**Comment by Whatsek** [comment]
I have the exact same issue

**Comment by epposan** [comment]
I manage a _Standard_ installation, but it shows the same error.
Reverting to version 0.4.5 seems to fix the issue ...

**Comment by TGgrimreaper** [comment]
Cam confirm 0.45 solves isseu
