### ISSUE TITLE
[BUG] warning in logs after update

### ISSUE THREAD

**Issue by cmseasy** [vincentwolsink/home_assistant_enphase_envoy_installer#162]
**Describe the bug**
After update to 0.4.8. my log gives:

Logger: homeassistant.components.sensor.recorder
Bron: components/sensor/recorder.py:327
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 11:25:11 (1 gebeurtenissen)
Laatst gelogd: 11:25:11

Entity sensor.envoy_122025007960_lifetime_energy_consumption_l3 from integration enphase_envoy has state class total_increasing, but its state is negative. Triggered by state -1259.672 with last_updated set to 2024-09-29T09:21:30.187820+00:00. Please create a bug report at https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/issues

Possibly caused by my gateway being in a sub-distributor. The CTs on the sub-distributer main switch also measure the feedback to the main distributor? And state_class is total_increase.

Possible solution: change state_class to total

**Account type**
- [ x] Installer
- [ ] DIY / DHZ
- [ ] Home Owner (This integration is not (fully) functional with a home owner account!)

**Envoy**
- [x ] Metered with CTs installed
- [ ] Metered without CTs
- [ ] Standard

- FW version: D7.xxx
- Amount of micro inverters connected: 14

**Home Assistant**
- Version: 2024.9.3

**Additional context**
```
Relevant snippet of Home Assistant error log. 
```

**Comment by cmseasy** [comment]
It is negative after installing the CT's on sept. 13.   On sept 18 I switched from HA integration Enphase Envoy (dev) to Enphase Envoy (installer)

![Screenshot 2024-09-29 at 15-35-26 Geschiedenis – Home Assistant](https://github.com/user-attachments/assets/60c83850-3847-4e92-9aff-a9ffc4be9c10)

Is I wrote the 3 phase metered gateway is mounted in a sub distributer. The L3 phase is not connected to anny device and only supplies to the main distributor. The other phases are used: L1: water pomp, L2: heat recovery unit.

The L3 descending metering is correct. I only supply back to the main distributor via phase L3.

Using a sub-divider is not unusual. Unfortunately, the consumption measurement is not the consumption of the grid but the consumption of the sub-distributor. I have no other option here. This is not a problem for monitoring grid consumption, I get this from the P1 meter.
Even YouTuber Ketel Klets has his gateway in a sub-distributor and mentions this in his video: https://www.youtube.com/watch?v=LnfeTiY7X_I starting from 5:45m. He mentions it as an advantage to switching off solar panels at negative prices.

That why I think the state_class "total" is better for these lifetime_energy_consumption sensors

**Comment by vincentwolsink** [comment]
I see. I also checked some Enphase [documentation](https://enphase.com/en-au/download/installing-two-iq-gateways-one-site-tech-brief) and this indeed seems the way to do it. For my understanding, could you maybe paste your output of `https://ENVOY_IP/production.json?details=1`?

**Comment by cmseasy** [comment]
Hi Vincent,

My production.json atteched.
[production._json.txt](https://github.com/user-attachments/files/17186890/production._json.txt)

Regards,
Martin
