### ISSUE TITLE
[BUG] Setup failed

### ISSUE THREAD

**Issue by julianvdhogen** [vincentwolsink/home_assistant_enphase_envoy_installer#164]
**Describe the bug**
Bij toevoegen integratie de volgende foutmelding: Config-flow kon niet geladen worden: {"message":"Invalid handler specified"}

**Account type**
- [ ] Installer
- [ ] DIY / DHZ
- [ X ] Home Owner (This integration is not (fully) functional with a home owner account!)
- [ X ] Installer API rights

**Envoy**
- [ X ] Metered with CTs installed
- [ ] Metered without CTs
- [ ] Standard

- FW version: D8.2.4225
- Amount of micro inverters connected: 12

**Home Assistant**
- Version: 2024.8.2

**Additional context**

Relevant snippet of Home Assistant error log. 
"Logger: homeassistant.config_entries
Bron: config_entries.py:2871
Eerst voorgekomen: 15:58:40 (2 gebeurtenissen)
Laatst gelogd: 16:04:18

Error occurred loading flow for integration enphase_envoy: cannot import name 'UnitOfReactivePower' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)"

**Comment by vincentwolsink** [comment]
Hi @julianvdhogen, this constant was changed in Home Assistant 2024.9.0. Please update HA or use an older version of the integration.

I will update the version requirement in the HACS manifest (I forgot) 🙂
