### ISSUE TITLE
Entities for firmware version

### ISSUE THREAD

**Issue by M66B** [vincentwolsink/home_assistant_enphase_envoy_installer#167]
**Describe the feature**
Entity for Envoy firmware version, and micro inverters firmware versions.
Currently, the firmware version is shown for a device, but there is no entity, which would be useful to monitor firmware updates.

**Account type**
- Installer

**Envoy**
- Standard
- FW version: D8.2.4225 (this is what it is about)
- Amount of micro inverters connected: 10

**Home Assistant**
- Version: 2024.10.3

**Comment by mnederlof** [comment]
Great feature, but only useful, if we know how to detect if a firmware update is available and how to trigger it.

Do you have any information on how that can be found / done?

**Comment by mnederlof** [comment]
but how do we know if there is a firmware update available? And also, the firmware is pushed by enphase, we as end-users/installers have very limited influence on that.

So in which api should we look for a firmware version that is available for the envoy in order to show that an update is even available?

**Comment by vincentwolsink** [comment]
I think @M66B wants to use it to know that (and when) the Envoy has automatically updated. Not if an update is available.

**Comment by M66B** [comment]
> I think @M66B wants to use it to know that (and when) the Envoy has automatically updated. Not if an update is available.

Indeed.

**Comment by vincentwolsink** [comment]
@M66B The sensors are available in [0.5.1](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/releases/tag/0.5.1)

**Comment by M66B** [comment]
@vincentwolsink Thanks. However, I use the master branch, living dangerously ;-)
