### ISSUE TITLE
[BUG] did i do something wrong?

### ISSUE THREAD

**Issue by Seaniemo** [vincentwolsink/home_assistant_enphase_envoy_installer#187]
**Describe the bug**
i see the update with the tip that HA creates new entity's with the same name but different ID's so its adviced to remove and readd the enphase enoy (installer) device to my HA. now i did this and some entities are not there anymore. i can nowhere find 
sensor.envoy_xxx_current_power_production for example. 

did i do something wrong.?

**Account type**
- [ ] Installer
- [x] DIY / DHZ
- [ ] Home Owner (This integration is not (fully) functional with a home owner account!)

**Envoy**
- [ ] Metered with CTs installed
- [ ] Metered without CTs
- [x] Standard

- FW version: D8.2,4264
- Amount of micro inverters connected: 9

**Home Assistant**
- Version: 2024.11.3

**Additional context**
``` i re added the integration when  no sun is shining 
Relevant snippet of Home Assistant error log. 
```

**Comment by TGgrimreaper** [comment]
Ha renamed it to sensor.envoy_xxx_current_power_production_2.

So long term stats is lost🥲

**Comment by mnederlof** [comment]
You can probably just rename the sensor name to without the `_2` and see your long term stats.

**Comment by TGgrimreaper** [comment]
Not working for me. Says already registered. Changed the old one to _1 and the new one removed _2 still same

**Comment by vincentwolsink** [comment]
You can rename and preserve your long term stats. Make sure the old sensor is deleted and remove the _2 from the new one. If that doesn’t work restart Home Assistant and try again.

**Comment by Seaniemo** [comment]
> You can rename and preserve your long term stats. Make sure the old sensor is deleted and remove the _2 from the new one. If that doesn’t work restart Home Assistant and try again.

Could you give me a step by step ? Because what I did ain't working. 

Would be really appreciated.

**Comment by vincentwolsink** [comment]
1. Remove your Envoy from the integration.
2. Restart Home Assistant.
3. Add your Envoy to the integration.

Should be this simple.

**Comment by Seaniemo** [comment]
> 1. Remove your Envoy from the integration.
> 2. Restart Home Assistant.
> 3. Add your Envoy to the integration.
> 
> Should be this simple.

Vincent, what i did was the following. 
1: update the integration
2: remove the integration
3: restart home assitant
4: add the integration. 

and for some reason this did not working and couldnt find current_power no more. 

should i not update ?

**Comment by vincentwolsink** [comment]
Can you please provide me with the diagnostics file from the integration?

**Comment by Seaniemo** [comment]
[config_entry-enphase_envoy-01JE480B6Q3WDT0D0PXAM6FRJK.json](https://github.com/user-attachments/files/17982081/config_entry-enphase_envoy-01JE480B6Q3WDT0D0PXAM6FRJK.json)
@vincentwolsink here is the diagnostics. i will restore my system again now. 

![HA](https://github.com/user-attachments/assets/d23c72bb-ea18-4273-9ec7-2e0b2471c646)
here you can see no more power production entity

**Comment by Seaniemo** [comment]
@vincentwolsink i just updated without removing. and now it just works. 

i will just delete the old un available entities...
