### ISSUE TITLE
[Feedback] initial setup dialog should mention Enlighten account

### ISSUE THREAD

**Issue by wernertgithub** [vincentwolsink/home_assistant_enphase_envoy_installer#49]
The help text of the 'username' - 'password' dialog is not clear IMHO. It mentions to uses 'envoy' or 'installer' as username, and last 6 digits of serial as password. However, almost all gateways (firmware v7) do not work with local logins anymore.
[Edit: The info is here, in the github repo, but it would be nice to also show it during setup.]

Request: please also mention that, if the 'envoy' or 'installer' login does not work, the user should try the Enlighten credentials.
Best solution: check firmware before displaying text, and act accordingly.

**Comment by vincentwolsink** [comment]
The configuration dialog should look like below. If this is not the case something went wrong during installation or you are using another variant of the Enphase Envoy integration. In that case, uninstall the integration, make sure the `custom_components/enphase_envoy` directory is gone and reinstall from HACS.

<img width="610" alt="Scherm­afbeelding 2023-07-23 om 12 15 58" src="https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/1639734/af6b0220-2b67-4149-92a3-94d6657e1a9d">
