### ISSUE TITLE
Add to HA energy dashboard

### ISSUE THREAD

**Issue by muldy** [vincentwolsink/home_assistant_enphase_envoy_installer#80]
Can't add "sensor.envoy_SERIAL_current_power_production" to the energy dashboard.
It's not showing up on the "Add Solar production" section.

Is there a way to add it?

**Comment by catsmanac** [comment]
Energy dashboard needs energy (Wh or J) entities, not power (W) entities. Isn't there an energy entity showing in the list like Lifetime Energy Production?

**Comment by muldy** [comment]
<img width="376" alt="image" src="https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/169374/f4e0a27c-0c0e-47b6-8d78-18106d0004a3">
Should I choose "Today's energy production" ?

Thank you

**Comment by catsmanac** [comment]
I have mine running on lifetime and that works fine.
![afbeelding](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/120491684/771feaf1-171a-497f-a4ef-e91be9c73207)

**Comment by muldy** [comment]
Thanks!
I get values now!

But something seems wrong: 
![Screenshot from 2023-08-05 10-33-26](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/169374/24e7098b-6f9f-41d2-83fd-bab289728247)

Main power is shelly clamp in the house's grid entry, it's showing a surplus, but the solar value on the graph does not reflect that (Solar should be more than 1.8 kwh? ).

**Comment by muldy** [comment]
I think I see it now, the "Energy distribution" distribution card are aggregate values.
Can close if this is true.

**Comment by catsmanac** [comment]
Energy dashboard takes a while before it shows all because it's running from history.

I can't close issues as bystander, you as originator can or @vincentwolsink.

**Comment by muldy** [comment]
thanks again!
