### ISSUE TITLE
Lifetime Energy Production starts at 0 after update

### ISSUE THREAD

**Issue by mvroosmalen1970** [vincentwolsink/home_assistant_enphase_envoy_installer#82]
**Describe the bug**

**Account type**
- [x] Installer
- [ ] DIY / DHZ
- [ ] Home Owner (This integration is not (fully) functional with a home owner account!)

**Envoy**
- [x] Metered with CTs installed
- [ ] Metered without CTs
- [ ] Standard

- FW version:  D7.6.175
- Amount of micro inverters connected: x

**Home Assistant**
- Version: 2023.8.1

This morning I decided to implement the latest version and after the update the Lifetime Energy Production starts at 0, causing high usage to be reported in the Energy usage graphs.

Relevant snippet of Home Assistant error log. 
![image](https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/36565907/79128062-9953-4fb6-b42c-00488bed636b)

**Comment by vincentwolsink** [comment]
Hi @mvroosmalen1970 looking at the picture to me it seems it was 0 before, and now back to the correct value. The firmware update to Envoys caused some reading errors for a lot of people (see also #40).

If the value is indeed correct now, you can fix the Energy dashboard graphs in HA with the following method:
1. Go to [Developer tools > Statistics](https://my.home-assistant.io/redirect/developer_statistics/).
2. Find the Envoy XXXX Lifetime Energy Production.
3. Click the little ramp icon on the right.
4. Go to the date/time where the huge increase happened.
5. Adjust the value there to 0 (or some other sane value).

**Comment by vincentwolsink** [comment]
Assuming this is now resolved. Otherwise you can re-open this issue.
